-- Vasfiy Market: boshlang'ich katalog (12 mahsulot, 4 til). Idempotent — qayta Run xavfsiz.
insert into public.settings(key, value) select 'extraCats', '{}'::jsonb where not exists (select 1 from public.settings where key='extraCats');
update public.settings set value = jsonb_set(coalesce(value,'{}'::jsonb), '{product}', coalesce(value->'product','{}'::jsonb) || '{"parfum": {"en": "Perfumes", "uz": "Parfyumeriya", "icon": "🌸"}, "charm": {"en": "Leather goods", "uz": "Charm buyumlar", "icon": "🧳"}, "kiyim": {"en": "Clothing", "uz": "Kiyim", "icon": "🧥"}, "poyabzal": {"en": "Shoes", "uz": "Poyabzal", "icon": "👞"}, "aksessuar": {"en": "Accessories", "uz": "Aksessuarlar", "icon": "⌚"}}'::jsonb) where key='extraCats';

insert into public.items (kind, data, position, pinned)
select 'product', '{"title": "Dior Sauvage EDP 100 ml", "titleUz": "Dior Sauvage parfyum suvi 100 ml", "titleRu": "Dior Sauvage парфюмерная вода 100 мл", "titleDe": "Dior Sauvage EDP 100 ml", "desc": "Original, sealed, EAN-coded — sourced from an authorized EU distributor. Delivery to Uzbekistan 7–14 days (pre-order).", "descUz": "Original, muhrlangan, EAN kodli — Yevropaning rasmiy distribyutoridan. O''zbekistonga yetkazish 7–14 kun (oldindan buyurtma).", "descRu": "Оригинал, запечатан, с EAN-кодом — от официального дистрибьютора ЕС. Доставка в Узбекистан 7–14 дней (предзаказ).", "descDe": "Original, versiegelt, mit EAN-Code — vom autorisierten EU-Händler. Lieferung nach Usbekistan 7–14 Tage (Vorbestellung).", "price": "122", "origin": "EU → UZ", "cat": "parfum", "currency": "EUR", "stock": "preorder", "images": [{"url": "/market-seed/sauvage.jpg", "name": "sauvage.jpg", "type": "image/jpeg"}]}'::jsonb, (select coalesce(max(position),0)+1 from public.items where kind='product'), false
where not exists (select 1 from public.items where kind='product' and data->>'title' = 'Dior Sauvage EDP 100 ml');
insert into public.items (kind, data, position, pinned)
select 'product', '{"title": "Bleu de Chanel EDP 100 ml", "titleUz": "Bleu de Chanel parfyum suvi 100 ml", "titleRu": "Bleu de Chanel парфюмерная вода 100 мл", "titleDe": "Bleu de Chanel EDP 100 ml", "desc": "Original, sealed, EAN-coded — sourced from an authorized EU distributor. Delivery to Uzbekistan 7–14 days (pre-order).", "descUz": "Original, muhrlangan, EAN kodli — Yevropaning rasmiy distribyutoridan. O''zbekistonga yetkazish 7–14 kun (oldindan buyurtma).", "descRu": "Оригинал, запечатан, с EAN-кодом — от официального дистрибьютора ЕС. Доставка в Узбекистан 7–14 дней (предзаказ).", "descDe": "Original, versiegelt, mit EAN-Code — vom autorisierten EU-Händler. Lieferung nach Usbekistan 7–14 Tage (Vorbestellung).", "price": "135", "origin": "EU → UZ", "cat": "parfum", "currency": "EUR", "stock": "preorder", "images": [{"url": "/market-seed/chanel.jpg", "name": "chanel.jpg", "type": "image/jpeg"}]}'::jsonb, (select coalesce(max(position),0)+1 from public.items where kind='product'), false
where not exists (select 1 from public.items where kind='product' and data->>'title' = 'Bleu de Chanel EDP 100 ml');
insert into public.items (kind, data, position, pinned)
select 'product', '{"title": "YSL Libre EDP 90 ml", "titleUz": "YSL Libre parfyum suvi 90 ml", "titleRu": "YSL Libre парфюмерная вода 90 мл", "titleDe": "YSL Libre EDP 90 ml", "desc": "Original, sealed, EAN-coded — sourced from an authorized EU distributor. Delivery to Uzbekistan 7–14 days (pre-order).", "descUz": "Original, muhrlangan, EAN kodli — Yevropaning rasmiy distribyutoridan. O''zbekistonga yetkazish 7–14 kun (oldindan buyurtma).", "descRu": "Оригинал, запечатан, с EAN-кодом — от официального дистрибьютора ЕС. Доставка в Узбекистан 7–14 дней (предзаказ).", "descDe": "Original, versiegelt, mit EAN-Code — vom autorisierten EU-Händler. Lieferung nach Usbekistan 7–14 Tage (Vorbestellung).", "price": "122", "origin": "EU → UZ", "cat": "parfum", "currency": "EUR", "stock": "preorder", "images": [{"url": "/market-seed/libre.jpg", "name": "libre.jpg", "type": "image/jpeg"}]}'::jsonb, (select coalesce(max(position),0)+1 from public.items where kind='product'), false
where not exists (select 1 from public.items where kind='product' and data->>'title' = 'YSL Libre EDP 90 ml');
insert into public.items (kind, data, position, pinned)
select 'product', '{"title": "Lattafa Khamrah EDP 100 ml", "titleUz": "Lattafa Khamrah parfyum suvi 100 ml", "titleRu": "Lattafa Khamrah парфюмерная вода 100 мл", "titleDe": "Lattafa Khamrah EDP 100 ml", "desc": "Original, sealed, EAN-coded — sourced from an authorized EU distributor. Delivery to Uzbekistan 7–14 days (pre-order).", "descUz": "Original, muhrlangan, EAN kodli — Yevropaning rasmiy distribyutoridan. O''zbekistonga yetkazish 7–14 kun (oldindan buyurtma).", "descRu": "Оригинал, запечатан, с EAN-кодом — от официального дистрибьютора ЕС. Доставка в Узбекистан 7–14 дней (предзаказ).", "descDe": "Original, versiegelt, mit EAN-Code — vom autorisierten EU-Händler. Lieferung nach Usbekistan 7–14 Tage (Vorbestellung).", "price": "30", "origin": "EU → UZ", "cat": "parfum", "currency": "EUR", "stock": "preorder", "images": [{"url": "/market-seed/khamrah.jpg", "name": "khamrah.jpg", "type": "image/jpeg"}]}'::jsonb, (select coalesce(max(position),0)+1 from public.items where kind='product'), false
where not exists (select 1 from public.items where kind='product' and data->>'title' = 'Lattafa Khamrah EDP 100 ml');
insert into public.items (kind, data, position, pinned)
select 'product', '{"title": "Italian leather handbag (Florence)", "titleUz": "Italyan charm ayollar sumkasi (Florensiya)", "titleRu": "Итальянская кожаная сумка (Флоренция)", "titleDe": "Italienische Lederhandtasche (Florenz)", "desc": "Genuine leather, handcrafted in Europe. Delivery to Uzbekistan 7–14 days (pre-order).", "descUz": "Haqiqiy teri, Yevropada qo''lda tayyorlangan. O''zbekistonga yetkazish 7–14 kun (oldindan buyurtma).", "descRu": "Натуральная кожа, ручная работа, Европа. Доставка в Узбекистан 7–14 дней (предзаказ).", "descDe": "Echtes Leder, handgefertigt in Europa. Lieferung nach Usbekistan 7–14 Tage (Vorbestellung).", "price": "85", "origin": "EU → UZ", "cat": "charm", "currency": "EUR", "stock": "preorder", "images": [{"url": "/market-seed/handbag.jpg", "name": "handbag.jpg", "type": "image/jpeg"}]}'::jsonb, (select coalesce(max(position),0)+1 from public.items where kind='product'), false
where not exists (select 1 from public.items where kind='product' and data->>'title' = 'Italian leather handbag (Florence)');
insert into public.items (kind, data, position, pinned)
select 'product', '{"title": "Men''s leather wallet (RFID)", "titleUz": "Erkaklar charm hamyoni (RFID)", "titleRu": "Мужской кожаный кошелёк (RFID)", "titleDe": "Herren-Ledergeldbörse (RFID)", "desc": "Genuine leather, handcrafted in Europe. Delivery to Uzbekistan 7–14 days (pre-order).", "descUz": "Haqiqiy teri, Yevropada qo''lda tayyorlangan. O''zbekistonga yetkazish 7–14 kun (oldindan buyurtma).", "descRu": "Натуральная кожа, ручная работа, Европа. Доставка в Узбекистан 7–14 дней (предзаказ).", "descDe": "Echtes Leder, handgefertigt in Europa. Lieferung nach Usbekistan 7–14 Tage (Vorbestellung).", "price": "32", "origin": "EU → UZ", "cat": "charm", "currency": "EUR", "stock": "preorder", "images": [{"url": "/market-seed/wallet.jpg", "name": "wallet.jpg", "type": "image/jpeg"}]}'::jsonb, (select coalesce(max(position),0)+1 from public.items where kind='product'), false
where not exists (select 1 from public.items where kind='product' and data->>'title' = 'Men''s leather wallet (RFID)');
insert into public.items (kind, data, position, pinned)
select 'product', '{"title": "Classic leather belt", "titleUz": "Klassik charm kamar", "titleRu": "Классический кожаный ремень", "titleDe": "Klassischer Ledergürtel", "desc": "Genuine leather, handcrafted in Europe. Delivery to Uzbekistan 7–14 days (pre-order).", "descUz": "Haqiqiy teri, Yevropada qo''lda tayyorlangan. O''zbekistonga yetkazish 7–14 kun (oldindan buyurtma).", "descRu": "Натуральная кожа, ручная работа, Европа. Доставка в Узбекистан 7–14 дней (предзаказ).", "descDe": "Echtes Leder, handgefertigt in Europa. Lieferung nach Usbekistan 7–14 Tage (Vorbestellung).", "price": "26", "origin": "EU → UZ", "cat": "charm", "currency": "EUR", "stock": "preorder", "images": [{"url": "/market-seed/belt.jpg", "name": "belt.jpg", "type": "image/jpeg"}]}'::jsonb, (select coalesce(max(position),0)+1 from public.items where kind='product'), false
where not exists (select 1 from public.items where kind='product' and data->>'title' = 'Classic leather belt');
insert into public.items (kind, data, position, pinned)
select 'product', '{"title": "Men''s leather jacket (EU made)", "titleUz": "Erkaklar charm kurtkasi (Yevropa)", "titleRu": "Мужская кожаная куртка (ЕС)", "titleDe": "Herren-Lederjacke (EU)", "desc": "Genuine leather, handcrafted in Europe. Delivery to Uzbekistan 7–14 days (pre-order).", "descUz": "Haqiqiy teri, Yevropada qo''lda tayyorlangan. O''zbekistonga yetkazish 7–14 kun (oldindan buyurtma).", "descRu": "Натуральная кожа, ручная работа, Европа. Доставка в Узбекистан 7–14 дней (предзаказ).", "descDe": "Echtes Leder, handgefertigt in Europa. Lieferung nach Usbekistan 7–14 Tage (Vorbestellung).", "price": "145", "origin": "EU → UZ", "cat": "kiyim", "currency": "EUR", "stock": "preorder", "images": [{"url": "/market-seed/jacket-men.jpg", "name": "jacket-men.jpg", "type": "image/jpeg"}]}'::jsonb, (select coalesce(max(position),0)+1 from public.items where kind='product'), false
where not exists (select 1 from public.items where kind='product' and data->>'title' = 'Men''s leather jacket (EU made)');
insert into public.items (kind, data, position, pinned)
select 'product', '{"title": "Women''s leather jacket (EU made)", "titleUz": "Ayollar charm kurtkasi (Yevropa)", "titleRu": "Женская кожаная куртка (ЕС)", "titleDe": "Damen-Lederjacke (EU)", "desc": "Genuine leather, handcrafted in Europe. Delivery to Uzbekistan 7–14 days (pre-order).", "descUz": "Haqiqiy teri, Yevropada qo''lda tayyorlangan. O''zbekistonga yetkazish 7–14 kun (oldindan buyurtma).", "descRu": "Натуральная кожа, ручная работа, Европа. Доставка в Узбекистан 7–14 дней (предзаказ).", "descDe": "Echtes Leder, handgefertigt in Europa. Lieferung nach Usbekistan 7–14 Tage (Vorbestellung).", "price": "135", "origin": "EU → UZ", "cat": "kiyim", "currency": "EUR", "stock": "preorder", "images": [{"url": "/market-seed/jacket-women.jpg", "name": "jacket-women.jpg", "type": "image/jpeg"}]}'::jsonb, (select coalesce(max(position),0)+1 from public.items where kind='product'), false
where not exists (select 1 from public.items where kind='product' and data->>'title' = 'Women''s leather jacket (EU made)');
insert into public.items (kind, data, position, pinned)
select 'product', '{"title": "Men''s leather shoes (Portugal)", "titleUz": "Erkaklar charm tuflisi (Portugaliya)", "titleRu": "Мужские кожаные туфли (Португалия)", "titleDe": "Herren-Lederschuhe (Portugal)", "desc": "Genuine leather, handcrafted in Europe. Delivery to Uzbekistan 7–14 days (pre-order).", "descUz": "Haqiqiy teri, Yevropada qo''lda tayyorlangan. O''zbekistonga yetkazish 7–14 kun (oldindan buyurtma).", "descRu": "Натуральная кожа, ручная работа, Европа. Доставка в Узбекистан 7–14 дней (предзаказ).", "descDe": "Echtes Leder, handgefertigt in Europa. Lieferung nach Usbekistan 7–14 Tage (Vorbestellung).", "price": "95", "origin": "EU → UZ", "cat": "poyabzal", "currency": "EUR", "stock": "preorder", "images": [{"url": "/market-seed/shoes-men.jpg", "name": "shoes-men.jpg", "type": "image/jpeg"}]}'::jsonb, (select coalesce(max(position),0)+1 from public.items where kind='product'), false
where not exists (select 1 from public.items where kind='product' and data->>'title' = 'Men''s leather shoes (Portugal)');
insert into public.items (kind, data, position, pinned)
select 'product', '{"title": "White sneakers (EU outlet)", "titleUz": "Oq krossovkalar (Yevropa autlet)", "titleRu": "Белые кроссовки (аутлет ЕС)", "titleDe": "Weiße Sneaker (EU-Outlet)", "desc": "Genuine leather, handcrafted in Europe. Delivery to Uzbekistan 7–14 days (pre-order).", "descUz": "Haqiqiy teri, Yevropada qo''lda tayyorlangan. O''zbekistonga yetkazish 7–14 kun (oldindan buyurtma).", "descRu": "Натуральная кожа, ручная работа, Европа. Доставка в Узбекистан 7–14 дней (предзаказ).", "descDe": "Echtes Leder, handgefertigt in Europa. Lieferung nach Usbekistan 7–14 Tage (Vorbestellung).", "price": "75", "origin": "EU → UZ", "cat": "poyabzal", "currency": "EUR", "stock": "preorder", "images": [{"url": "/market-seed/sneakers.jpg", "name": "sneakers.jpg", "type": "image/jpeg"}]}'::jsonb, (select coalesce(max(position),0)+1 from public.items where kind='product'), false
where not exists (select 1 from public.items where kind='product' and data->>'title' = 'White sneakers (EU outlet)');
insert into public.items (kind, data, position, pinned)
select 'product', '{"title": "Classic watch, leather strap", "titleUz": "Klassik qo''l soati (charm tasma)", "titleRu": "Классические часы, кожаный ремешок", "titleDe": "Klassische Uhr mit Lederband", "desc": "Genuine leather, handcrafted in Europe. Delivery to Uzbekistan 7–14 days (pre-order).", "descUz": "Haqiqiy teri, Yevropada qo''lda tayyorlangan. O''zbekistonga yetkazish 7–14 kun (oldindan buyurtma).", "descRu": "Натуральная кожа, ручная работа, Европа. Доставка в Узбекистан 7–14 дней (предзаказ).", "descDe": "Echtes Leder, handgefertigt in Europa. Lieferung nach Usbekistan 7–14 Tage (Vorbestellung).", "price": "68", "origin": "EU → UZ", "cat": "aksessuar", "currency": "EUR", "stock": "preorder", "images": [{"url": "/market-seed/watch.jpg", "name": "watch.jpg", "type": "image/jpeg"}]}'::jsonb, (select coalesce(max(position),0)+1 from public.items where kind='product'), false
where not exists (select 1 from public.items where kind='product' and data->>'title' = 'Classic watch, leather strap');

select data->>'title' as title, data->>'price' as price, data->>'cat' as cat from public.items where kind='product' order by position;